export const CONCESSIONARIAS = [
  "GOINFRA",
  "EQTL",
  "VSBTE - VALE DO SÃO BARTOLOMEU",
  "ECOVIAS DO ARAGUAIA",
  "STATE GRID",
  "DNIT",
  "TRIUNFO CONCEBRA",
  "PCH MAMBAÍ II",
  "CARNAÚBA ENERGIA S.A",
  "BRENCO - ATVOS",
  "RUMO",
  "ENERGISA",
  "EDP",
  "ELETROBRAS/FURNAS",
  "ECO-050",
  "FIRMINÓPOLIS TRANSMISSORA",
  "BELO MONTE",
  "ECOVIAS DO CERRADO",
  "VLI - CENTRO ATLANTICA",
  "TECPAV ROTA VERDE",
  "SEFAC",
  "GOIAS SUL GERAÇAO DE ENERGIA S/A",
  "NORTE BRASIL TRANSMISSORA",
  "CATXERE",
  "GTE – GUARACIABA TRANSMISSORA DE ENERGIA S A",
  "ITUMBIARA TRANSMISSORA DE ENERGIA S.A",
  "TAESA",
  "VALEC/INFRA",
  "ESSENTIA ENERGIA",
  "GOIÁS TRANSMISSÃO S.A",
  "ESPORA ENERGÉTICA S.A",
  "INTEGRAÇÃO TRANSMISSORA DE ENERGIA",
  "KINROSS MINERAÇÃO",
  "RIO VERDE S.A",
  "TRANSENERGIA",
  "VIA CRISTAIS",
  "BP BIOENERGIA ITUMBIARA S.A",
  "BRENTECH",
  "PARANAÍBA TRANSMISSORA DE ENERGIA S.A",
  "IEM - INTERLIGAÇÃO ELETRICA DO MADEIRA S.A",
  "CHESP",
  "PCH Irara/Cabriúva – Irara Energética",
  "ENGIE",
  "AUREN ENERGIA",
  "LAGO AZUL TRANSMISSORA",
  "NEOENERGIA"
].sort();

export const STATUS_COLORS: Record<string, string> = {
  'NÃO INICIADO': 'bg-gray-100 text-gray-700 border-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-700',
  'NOVO': 'bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-800',
  'EM ANÁLISE': 'bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-400 dark:border-indigo-800',
  'TRIAGEM': 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-400 dark:border-purple-800',
  'PREVISÃO DE BOLETO': 'bg-yellow-100 text-yellow-700 border-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-400 dark:border-yellow-800',
  'AGUARDANDO PAGAMENTO': 'bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-900/30 dark:text-orange-400 dark:border-orange-800',
  'APROVADO': 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-400 dark:border-green-800',
  'REPROVADO': 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800',
  'CANCELADO': 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800',
  'PROTOCOLADO': 'bg-teal-100 text-teal-700 border-teal-200 dark:bg-teal-900/30 dark:text-teal-400 dark:border-teal-800',
  'EM TRATATIVA': 'bg-pink-100 text-pink-700 border-pink-200 dark:bg-pink-900/30 dark:text-pink-400 dark:border-pink-800',
  'CORREÇÃO': 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-400 dark:border-amber-800',
  'EM ELABORAÇÃO': 'bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-900/30 dark:text-cyan-400 dark:border-cyan-800',
  // Support mixed cases if needed, but looks like it's strictly uppercase.
};
