// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/admin" | "/dashboard/ambiental" | "/dashboard/anuencia" | "/dashboard/operacional" | "/dashboard/travessia" | "/reset-password"
type AppRouteHandlerRoutes = "/api/history" | "/api/processes" | "/api/processes/import-status" | "/api/processes/update" | "/api/processes/update-observation" | "/api/processes/update-status" | "/api/processes/update-taxa" | "/api/processes/upload-attachment" | "/api/protocol" | "/api/seed"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/dashboard/admin" | "/dashboard/ambiental" | "/dashboard/anuencia" | "/dashboard/travessia"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/history": {}
  "/api/processes": {}
  "/api/processes/import-status": {}
  "/api/processes/update": {}
  "/api/processes/update-observation": {}
  "/api/processes/update-status": {}
  "/api/processes/update-taxa": {}
  "/api/processes/upload-attachment": {}
  "/api/protocol": {}
  "/api/seed": {}
  "/dashboard": {}
  "/dashboard/admin": {}
  "/dashboard/ambiental": {}
  "/dashboard/anuencia": {}
  "/dashboard/operacional": {}
  "/dashboard/travessia": {}
  "/reset-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/dashboard/admin": never
  "/dashboard/ambiental": never
  "/dashboard/anuencia": never
  "/dashboard/travessia": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
