// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ambiental/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ambiental">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ambiental/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/anuencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/anuencia">> = Specific
  const handler = {} as typeof import("../../app/dashboard/anuencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/operacional/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/operacional">> = Specific
  const handler = {} as typeof import("../../app/dashboard/operacional/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/travessia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/travessia">> = Specific
  const handler = {} as typeof import("../../app/dashboard/travessia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/import-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes/import-status">> = Specific
  const handler = {} as typeof import("../../app/api/processes/import-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes">> = Specific
  const handler = {} as typeof import("../../app/api/processes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/update-observation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes/update-observation">> = Specific
  const handler = {} as typeof import("../../app/api/processes/update-observation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/update-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes/update-status">> = Specific
  const handler = {} as typeof import("../../app/api/processes/update-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/update-taxa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes/update-taxa">> = Specific
  const handler = {} as typeof import("../../app/api/processes/update-taxa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes/update">> = Specific
  const handler = {} as typeof import("../../app/api/processes/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/processes/upload-attachment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/processes/upload-attachment">> = Specific
  const handler = {} as typeof import("../../app/api/processes/upload-attachment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/protocol/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protocol">> = Specific
  const handler = {} as typeof import("../../app/api/protocol/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed">> = Specific
  const handler = {} as typeof import("../../app/api/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/dashboard/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ambiental/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/ambiental">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ambiental/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/anuencia/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/anuencia">> = Specific
  const handler = {} as typeof import("../../app/dashboard/anuencia/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/travessia/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/travessia">> = Specific
  const handler = {} as typeof import("../../app/dashboard/travessia/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
